# One pod, one container
# Asking for 2 distinct GPUs with matching driver version

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test7

---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test7
  name: multiple-gpus
spec:
  spec:
    devices:
      requests:
      - name: gpus
        deviceClassName: gpu.example.com
        allocationMode: ExactCount
        count: 2
      constraints:
      - requests: ["gpus"]
        MatchExpression: "size(devices) == 2 && devices.exists(first, devices.exists(second, first != second && (first.attributes['gpu.example.com'].index == second.attributes['gpu.example.com'].index + 1 || first.attributes['gpu.example.com'].index == second.attributes['gpu.example.com'].index - 1)))"
      - requests: ["gpus"]
        matchAttribute: "gpu.example.com/driverVersion"
---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test7
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: gpus
  resourceClaims:
  - name: gpus
    resourceClaimTemplateName: multiple-gpus
